Fix threshold test in Safe.create()
safe-global/safe-eth-py pull request #274
Opened 2022-06-22 01:11 UTC by DefiDebauchery

`Safe.create()` currently asserts that the threshold is equal or greater than the list of owners, which is nonsensical. The Safe threshold can be any number of signers, logically up to the maximum number defined.

2022-06-28 12:13 UTC, Uxio0 commented
> I have read the CLA Document and I hereby sign the CLA
> 
> (By the way, you do not actually have a CLA - the bot points to https://github.com/safe.global/cla/, which returns 404)

That's weird, it should point to https:/safe.global/cla/

2022-06-28 12:14 UTC, Uxio0 commented
Indeed, there was a typo. Thanks for the PR and the CLA!

2022-07-04 14:27 UTC, Uxio0 requested changes

2022-07-04 14:27 UTC, Uxio0 commented on gnosis/safe/safe.py
> +        assert threshold <= len(owners), "Threshold=%d must be <= %d" % (
Could you do `assert 1 <= threshold <= len(owners)`

2022-07-07 11:18 UTC, Uxio0 commented
Hi @DefiDebauchery , could you rebase `master` and do the proposed change so I can merge this? 🙏🏻 ? Thanks a lot!

2022-07-10 01:38 UTC, DefiDebauchery commented
Rebased and pushed.

2022-07-10 11:00 UTC, Uxio0 commented
> Rebased and pushed.

Thanks but you missed the change request 😅 

> Could you do assert `1 <= threshold <= len(owners)` ?

2022-07-11 19:36 UTC, DefiDebauchery commented
Sorry about that. Updated.

2022-07-12 10:27 UTC, Uxio0 commented
> Sorry about that. Updated.

Not at all, thank you very much!

2022-07-12 10:27 UTC, Uxio0 approved these changes

2022-07-12 11:07 UTC, merged