Add Haqq networks
safe-global/safe-eth-py pull request #730
Opened 2024-01-09 12:24 UTC by Hirama

Please add Haqq Mainnet and HaqqTestnet:

https://github.com/safe-global/safe-deployments/pull/335

Thank you!

2024-01-09 12:30 UTC, Hirama commented
I have read the CLA Document and I hereby sign the CLA

2024-01-15 14:08 UTC, moisses89 requested changes
Thanks for your contribution, could you check the addresses?

2024-01-15 14:08 UTC, moisses89 commented on gnosis/safe/addresses.py
> +        ("0xfb1bffC9d739B8D520DaF37dF666da4C687191EA", 422246, "1.3.0+L2"),
Address for L2 is different on Safe Deployments. https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/gnosis_safe_l2.json#L124

2024-01-16 08:49 UTC, Hirama commented
@moisses89 thanks for comments! I have applied fixes.

2024-01-23 15:43 UTC, moisses89 approved these changes

2024-01-23 15:44 UTC, moisses89 commented
@Hirama could you fix the conflicts, ping me when ready.

2024-01-23 18:32 UTC, Hirama commented
@moisses89 resolved, please check

2024-01-23 18:37 UTC, Hirama commented
@moisses89 resolved, please check

2024-01-24 09:46 UTC, merged